### ISSUE TITLE
callback retries

### ISSUE THREAD

**Issue by tojepil** [QuickPay/QuickPay.github.io#34]
Godmorgen. På callback-siden skriver I:
sthing
Mener I i øvrigt 24 gange i løbet af én time, eller 24 gange med en times mellemrum mellem hvert forsøg?
tj
hvad skriver vi ? - det kom vist aldrig
tj
men det er en gang i timen i et døgn
tl has changed mode: -v tl  away
sthing
Må jeg foreslå en omformulering så? ..., the callback service will retry to deliver its message up to 24 times with a 1 hour interval. til => will, in a => with a.
sthing
I skriver at I har op til 24 retries - men jeg har ingen fået på fx  https://manage.quickpay.net/#/account/333/payments/7379366   Er retry seystemet broken?

**Comment by ta** [comment]
Reformulated - the retry issue is old and likely fixed
